name: dbt BigQuery

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    paths:
      - models/**
      - seeds/**
      - tests/**

env:
  # dbt env variables used in your dbt profiles.yml
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: ${{ vars.DBT_GOOGLE_PROJECT }}
  DBT_GOOGLE_DATASET: ${{ vars.DBT_GOOGLE_DATASET }}
  DBT_GOOGLE_KEYFILE: /tmp/google/google-service-account.json
  
  # the contents of the keyfile pulled from GitHub Actions secrets 
  KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}

jobs:
  build:
    name: install and build dbt
    runs-on: ubuntu-latest

    steps:

      # Prep Google keyfile
      - run: mkdir -p "$(dirname $DBT_GOOGLE_KEYFILE)" 
      - run: echo "$KEYFILE_CONTENTS" > $DBT_GOOGLE_KEYFILE
    
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dbt
        run: |
          pip install dbt-bigquery
          dbt deps
          dbt --version

      - name: Run dbt
        run: dbt build