default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: [INSERT PROJECT NAME]
      dataset: [INSERT SCHEMA]
      timeout_seconds: 300
      location: US
      priority: interactive
